name: CoarizWildTP
version: 1.0
main: com.coariz.coarizwildtp.CoarizWildTP
api-version: 1.21
commands:
  wild:
    description: Teleports you to a random safe location.
    aliases:
      - rtp
  coarizwildtp:
    description: Manages CoarizWildTP plugin commands.
    usage: /<command> <subcommand>
    subcommands:
      reload:
        description: Reloads the plugin configuration.
        permission: coarizwildtp.reload
permissions:
  coarizwildtp.use:
    description: Allows the player to use the /wild command.
    default: op
  coarizwildtp.reload:
    description: Allows the admin to reload the plugin configuration.
    default: op